language: ruby
rvm:
 - 2.5.1
 - 2.4.4
 - 2.3.7
 - 2.2.10
 - 2.1.10
 - 2.0.0
 - 1.9.3
before_deploy:
 - rvm 1.9.3 do gem install mime-types -v 2.6.2
 - rvm 1.9.3 do gem install httparty -v 0.14.0
script: bundle exec rspec
matrix:
  allow_failures:
  - rvm: 1.9.3